var SETTINGS_NAME_TO_REPLACE = 'replace';
var SETTINGS_PLACEHOLDER = '[*]';

// Defaults

var SETTINGS_TEMPLATE = '0001-[*]';
var SETTINGS_PAD_STRING = '0';
var SETTINGS_PAD_SIZE = 4;

var SETTINGS_NUMBER_FROM = 1;
var SETTINGS_NUMBER_TO = 10;
var SETTINGS_NUMBER_STEP = 1;



