SETTINGS_NAME_TO_REPLACE = 'replace';
SETTINGS_PLACEHOLDER = '[*]';
SETTINGS_PAD_STRING = '0';

DEFAULT_TEMPLATE = '0001-[*]';
DEFAULT_PAD_SIZE = 4;

DEFAULT_NUMBER_FROM = 1;
DEFAULT_NUMBER_TO = 10;
DEFAULT_NUMBER_STEP = 1;